export { default as Agency } from './Agency';
export { default as Account } from './Account';
export { default as Ecommerce } from './Ecommerce';
export { default as NewHome } from './NewHome';
export { default as NotFound } from './NotFound';
export { default as NotFoundCover } from './NotFoundCover';
export { default as SigninCover } from './SigninCover';
export { default as SignupCover } from './SignupCover';
export { default as Startup } from './Startup';